server:
  port: 8183
spring:
  application:
    name: energy-dubbo

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${NACOS_ADDRESS:nacos.energy.com:8848}
    group: ${NACOS_GROUP:app}
    parameters:
      namespace: ${NACOS_NAMESPACE:energy}
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 30000
  consumer:
    timeout: 30000
