server:
  port: 8183
spring:
  application:
    name: energy-dubbo

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://nacos.energy.com:8848
    group: app
    parameters:
      namespace: energy
  protocol:
    name: dubbo
    port: -1
  provider:
    timeout: 30000
  consumer:
    timeout: 30000
