server:
  port: 8184
spring:
  application:
    name: energy-server

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://nacos.energy.com:8848
    group: app
    parameters:
      namespace: energy
  protocol:
    name: dubbo
  provider:
    timeout: 30000
    retries: 2
  consumer:
    timeout: 30000
    retries: 2